In [40]:
import pandas as pd
import numpy as np


Question 1

In [2]:
pd.__version__

'1.5.3'

Question 2

In [28]:
df=pd.read_csv(r'C:\Users\Pedro.dias\Downloads\housing.txt')

In [8]:
len(df.columns)

10

Question 3

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


Question 4

In [10]:
len(df[['ocean_proximity']].drop_duplicates())

5

Question 5

In [12]:
df.groupby(['ocean_proximity']).count()

longitude  latitude  housing_median_age  total_rooms  \
ocean_proximity                                                         
<1H OCEAN             9136      9136                9136         9136   
INLAND                6551      6551                6551         6551   
ISLAND                   5         5                   5            5   
NEAR BAY              2290      2290                2290         2290   
NEAR OCEAN            2658      2658                2658         2658   

                 total_bedrooms  population  households  median_income  \
ocean_proximity                                                          
<1H OCEAN                  9034        9136        9136           9136   
INLAND                     6496        6551        6551           6551   
ISLAND                        5           5           5              5   
NEAR BAY                   2270        2290        2290           2290   
NEAR OCEAN                 2628        2658        2658           2658   

                 median_house_value  
ocean_proximity                      
<1H OCEAN                      9136  
INLAND                         6551  
ISLAND                            5  
NEAR BAY                       2290  
NEAR OCEAN                     2658

In [13]:
df1=df.copy()

df1=df1[df1['ocean_proximity']=='NEAR BAY']
df1.groupby(['ocean_proximity']).agg({'median_house_value':'mean'})

median_house_value
ocean_proximity                    
NEAR BAY               259212.31179

Question 6

In [29]:
df1=df.copy()
m=df1['total_bedrooms'].mean()
m

537.8705525375618

In [30]:
df1[df1['total_bedrooms'].isnull()]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0             NaN   
341      -122.17     37.75                38.0        992.0             NaN   
538      -122.28     37.78                29.0       5154.0             NaN   
563      -122.24     37.75                45.0        891.0             NaN   
696      -122.10     37.69                41.0        746.0             NaN   
...          ...       ...                 ...          ...             ...   
20267    -119.19     34.20                18.0       3620.0             NaN   
20268    -119.18     34.19                19.0       2393.0             NaN   
20372    -118.88     34.17                15.0       4260.0             NaN   
20460    -118.75     34.29                17.0       5512.0             NaN   
20484    -118.72     34.28                17.0       3051.0             NaN   

       population  households  median_income  median_house_value  \
290         570.0       218.0         4.3750            161900.0   
341         732.0       259.0         1.6196             85100.0   
538        3741.0      1273.0         2.5762            173400.0   
563         384.0       146.0         4.9489            247100.0   
696         387.0       161.0         3.9063            178400.0   
...           ...         ...            ...                 ...   
20267      3171.0       779.0         3.3409            220500.0   
20268      1938.0       762.0         1.6953            167400.0   
20372      1701.0       669.0         5.1033            410700.0   
20460      2734.0       814.0         6.6073            258100.0   
20484      1705.0       495.0         5.7376            218600.0   

      ocean_proximity  
290          NEAR BAY  
341          NEAR BAY  
538          NEAR BAY  
563          NEAR BAY  
696          NEAR BAY  
...               ...  
20267      NEAR OCEAN  
20268      NEAR OCEAN  
20372       <1H OCEAN  
20460       <1H OCEAN  
20484       <1H OCEAN  

[207 rows x 10 columns]

In [31]:
df1['total_bedrooms']=df1['total_bedrooms'].fillna(m)

In [32]:
df1['total_bedrooms'].mean()

537.8705525375617

Question 7

In [34]:
df1=df.copy()

df1=df1[df1['ocean_proximity']=='ISLAND']
df1=df1[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [35]:
df1.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [58]:
X=df1.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [65]:
X_transpose = X.T

In [67]:
X_transpose

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [68]:
XTX=X_transpose @ X

In [69]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [70]:
inverse_XTX = np.linalg.inv(XTX)

In [71]:
y = np.array([950, 1300, 800, 1000, 1300])

In [72]:
inverse_XTX * X_transpose

ValueError: operands could not be broadcast together with shapes (3,3) (3,5) 